
import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import type { Post, User, Comment } from '@/lib/types';
import { categorizeContent, CategorizeContentInput } from '@/ai/flows/smart-content-categorization';
import { intelligentContentModeration, IntelligentContentModerationInput } from '@/ai/flows/intelligent-content-moderation';
import getDb from '@/lib/mongodb';
import { ObjectId } from 'mongodb';

// Schema for validating POST request body
const postFormSchema = z.object({
  userId: z.string().refine(val => ObjectId.isValid(val), { message: "Invalid User ID format." }),
  title: z.string().max(150, "Title can't exceed 150 characters.").optional(),
  content: z.string().min(1, 'Content is required.').max(5000, "Content can't exceed 5000 characters."),
  category: z.string().optional(),
  tags: z.string().optional(), // Comma-separated string
  isDraft: z.boolean().default(false),
  scheduledAt: z.string().datetime({ offset: true }).optional(),
});

// Define the structure of post documents in the database
type DbPost = Omit<Post, 'id' | 'author' | 'comments' | 'isLikedByCurrentUser' | 'isBookmarkedByCurrentUser' | 'authorId' | 'likedBy' | 'commentIds'> & {
  _id: ObjectId;
  authorId: ObjectId;
  likedBy: ObjectId[];
  commentIds: ObjectId[];
};
type DbComment = Omit<Comment, 'id' | 'author' | 'authorId' | 'postId'> & {
  _id: ObjectId;
  authorId: ObjectId;
  postId: ObjectId;
};


export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    
    const validation = postFormSchema.safeParse(body);
    if (!validation.success) {
      return NextResponse.json({ message: 'Invalid post data.', errors: validation.error.flatten().fieldErrors }, { status: 400 });
    }
    const data = validation.data;

    const db = await getDb();
    const usersCollection = db.collection<User>('users');
    const currentUserDoc = await usersCollection.findOne({ _id: new ObjectId(data.userId) }, {projection: {passwordHash: 0}});

    if (!currentUserDoc) {
        return NextResponse.json({ message: 'User not found. Cannot create post.' }, { status: 404 });
    }
    const currentUser: User = {...currentUserDoc, id: currentUserDoc._id!.toHexString() };


    const moderationInput: IntelligentContentModerationInput = { content: data.content, sensitivityLevel: 'medium' };
    const moderationResult = await intelligentContentModeration(moderationInput);
    if (moderationResult.isFlagged) {
      return NextResponse.json({
        message: `Post flagged by content moderation: ${moderationResult.reason}. Please revise.`,
        isFlagged: true,
        reason: moderationResult.reason,
      }, { status: 400 });
    }

    let finalCategory = data.category;
    let finalTagsArray = data.tags ? data.tags.split(',').map(tag => tag.trim()).filter(tag => tag) : [];

    if (!finalCategory || finalTagsArray.length === 0) {
        const categorizationInput: CategorizeContentInput = { content: data.content };
        try {
            const categorizationResult = await categorizeContent(categorizationInput);
            if (!finalCategory && categorizationResult.category) {
                finalCategory = categorizationResult.category;
            }
            if (finalTagsArray.length === 0 && categorizationResult.tags.length > 0) {
                finalTagsArray = [...new Set([...finalTagsArray, ...categorizationResult.tags])];
            }
        } catch (aiError) {
            console.warn("AI categorization failed, proceeding with user input or defaults:", aiError);
        }
    }

    const newPostDocument = {
      authorId: new ObjectId(data.userId),
      title: data.title,
      content: data.content,
      category: finalCategory,
      tags: finalTagsArray,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      likedBy: [], 
      likeCount: 0,
      commentIds: [], 
      commentCount: 0,
      status: data.isDraft ? 'draft' : (data.scheduledAt ? 'scheduled' : 'published'),
      scheduledAt: data.scheduledAt ? new Date(data.scheduledAt).toISOString() : undefined,
      // _id will be generated by MongoDB
    };

    const postsCollection = db.collection<Omit<DbPost, '_id'>>('posts'); // Type for insertion
    const result = await postsCollection.insertOne(newPostDocument);

    if (!result.insertedId) {
        throw new Error('Failed to insert post into database.');
    }
    
    const createdPostForClient: Post = {
        ...newPostDocument,
        _id: result.insertedId,
        id: result.insertedId.toHexString(),
        authorId: newPostDocument.authorId, 
        author: currentUser, 
        comments: [], 
        likedBy: [], // Return as empty string array for client if needed, or ObjectIds
        likeCount: 0,
        commentIds: [],
        commentCount: 0
    };

    return NextResponse.json({ message: 'Post created successfully!', post: createdPostForClient }, { status: 201 });

  } catch (error) {
    console.error('API Error creating post:', error);
    const errorMessage = error instanceof Error ? error.message : 'An unexpected error occurred.';
    return NextResponse.json({ message: errorMessage }, { status: 500 });
  }
}


export async function GET(request: NextRequest) {
  try {
    const db = await getDb();
    const postsCollection = db.collection<DbPost>('posts');
    const usersCollection = db.collection<User>('users');
    const commentsCollection = db.collection<DbComment>('comments');
    
    const { searchParams } = new URL(request.url);
    const authorId = searchParams.get('authorId');
    const bookmarkedById = searchParams.get('bookmarkedById');
    const forUserId = searchParams.get('forUserId'); // To determine 'isLikedByCurrentUser' and 'isBookmarkedByCurrentUser'

    let query: any = { status: 'published' }; // Default to published posts
    if (authorId && ObjectId.isValid(authorId)) {
      query.authorId = new ObjectId(authorId);
      // If fetching for a specific author, drafts/scheduled might be relevant
      // For simplicity, keeping 'published' default unless specified otherwise
      // query = { authorId: new ObjectId(authorId) }; 
    }

    let currentUser: User | null = null;
    if (forUserId && ObjectId.isValid(forUserId)) {
        currentUser = await usersCollection.findOne({ _id: new ObjectId(forUserId) });
    }


    if (bookmarkedById && ObjectId.isValid(bookmarkedById)) {
        const userWithBookmarks = await usersCollection.findOne({ _id: new ObjectId(bookmarkedById) });
        if (userWithBookmarks && userWithBookmarks.bookmarkedPostIds && userWithBookmarks.bookmarkedPostIds.length > 0) {
            query._id = { $in: userWithBookmarks.bookmarkedPostIds.map(id => new ObjectId(id)) };
        } else {
            return NextResponse.json([], { status: 200 }); // No bookmarked posts or user not found
        }
    }


    const postsFromDb = await postsCollection.find(query).sort({ createdAt: -1 }).toArray();

    const enrichedPosts: Post[] = await Promise.all(
      postsFromDb.map(async (postDoc) => {
        const authorDoc = await usersCollection.findOne({ _id: new ObjectId(postDoc.authorId) }, {projection: {passwordHash: 0}});
        
        const authorForClient: User | undefined = authorDoc ? {
          ...authorDoc,
          id: authorDoc._id.toHexString(),
          bookmarkedPostIds: authorDoc.bookmarkedPostIds?.map(id => new ObjectId(id)) || [],
        } : undefined;
        
        // Fetch first 2 comments for the post
        const recentCommentsDocs = await commentsCollection
            .find({ postId: postDoc._id })
            .sort({ createdAt: -1 })
            .limit(2)
            .toArray();

        const recentCommentsPopulated: Comment[] = await Promise.all(
            recentCommentsDocs.map(async (commentDoc) => {
                const commentAuthorDoc = await usersCollection.findOne({_id: commentDoc.authorId}, {projection: {passwordHash: 0}});
                return {
                    ...commentDoc,
                    id: commentDoc._id.toHexString(),
                    postId: commentDoc.postId,
                    authorId: commentDoc.authorId,
                    author: commentAuthorDoc ? { ...commentAuthorDoc, id: commentAuthorDoc._id.toHexString() } : undefined,
                } as Comment;
            })
        );
        
        const isLikedByCurrentUser = currentUser ? postDoc.likedBy.some(id => id.equals(currentUser!._id!)) : false;
        const isBookmarkedByCurrentUser = currentUser ? currentUser.bookmarkedPostIds?.some(id => id.equals(postDoc._id)) : false;

        return {
          ...postDoc,
          id: postDoc._id.toHexString(),
          authorId: postDoc.authorId, 
          author: authorForClient || { id: 'unknown', name: 'Unknown User', email:'', reputation: 0, joinedDate: new Date().toISOString() } as User,
          likedBy: postDoc.likedBy.map(id => new ObjectId(id)), // Keep as ObjectId for server, convert if needed for client
          likeCount: postDoc.likeCount,
          isLikedByCurrentUser,
          commentIds: postDoc.commentIds?.map((id: ObjectId | string) => typeof id === 'string' ? new ObjectId(id) : id) || [],
          comments: recentCommentsPopulated.reverse(), // Show oldest of the two first
          commentCount: postDoc.commentCount,
          isBookmarkedByCurrentUser,
        } as Post;
      })
    );

    return NextResponse.json(enrichedPosts, { status: 200 });
  } catch (error) {
    console.error('API Error fetching posts:', error);
    const errorMessage = error instanceof Error ? error.message : 'An unexpected error occurred.';
    return NextResponse.json({ message: errorMessage }, { status: 500 });
  }
}

